# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hsluv_rgb <- function(hsl) {
    .Call(`_HSLuv_hsluv_rgb`, hsl)
}

hsluv_hex <- function(h, s, l) {
    .Call(`_HSLuv_hsluv_hex`, h, s, l)
}

